### ISSUE TITLE
Mid-2012 Retina MBP 15" - "InstallAssistant is damaged"

### ISSUE THREAD

**Issue by zombienm** [BenSova/Patched-Sur#225] opened 2021-01-28 04:27 UTC
Every time I try to boot into recovery to install BigSur, I get the notification that the InstallAssistant is damaged and can not be used. I've tried downloading it directly from Apple and then patching it, and also using Patched-Sur to download it. Everything I try gets the same issue. Does anyone know how to solve this?

**Comment by BenSova** [comment] 2021-01-28 05:41
This is a duplicate of #100. There was a lot of discussion regarding this issue there.

**Closed by BenSova** 2021-01-28 05:41 UTC
Labels: bug
