### ISSUE TITLE
Error 1x1 while trying to patch kexts

### ISSUE THREAD

**Issue by BlueG6o** [BenSova/Patched-Sur#63] opened 2020-11-18 16:40 UTC
![Error](https://user-images.githubusercontent.com/74673121/99559448-186c9f00-29c5-11eb-95ad-809e1b5552ce.png)

I get the error on the picture when I try to patch the kexts. I know the solution is in the picture, but I don't know how to boot this refi utility and what to do.

**Comment by BenSova** [comment] 2020-11-18 18:42
It's the same yellow EFI Boot drive that you booted into before. Your Mac will instantly turn off once you boot into it, so just turn it on after that and try again.

This is also a duplicate of #27, where that solution did not work.

**Comment by BlueG6o** [comment] 2020-11-18 18:47
Thanx for the quick reply. I‘ve done that already. It didnt work for me. 👎

**Comment by BenSova** [comment] 2020-11-18 19:39
Well, either way it is a duplicate of #27, so I'm going to close it.

**Closed** 2020-11-18 19:39 UTC
