### ISSUE TITLE
Error 1x1 when patching Kexts

### ISSUE THREAD

**Issue by SineFromAbove** [BenSova/Patched-Sur#61] opened 2020-11-17 21:27 UTC
I successfully updated from Catalina to Big Sur on my late 2013 iMac but when I go to the post-install app to patch the Kexts it gives me this error. How do I fix it?

![Schermata 2020-11-17 alle 22 26 24](https://user-images.githubusercontent.com/74627024/99452549-f4a54c80-2923-11eb-818f-b31a2d9a125e.png)

**Comment by BenSova** [comment] 2020-11-17 21:48
This is a duplicate of #27.

**Closed** 2020-11-17 21:49 UTC
Labels: duplicate
