### ISSUE TITLE
ScreenSavers

### ISSUE THREAD

**Issue by Antixxxf** [BenSova/Patched-Sur#521] opened 2021-05-01 20:14 UTC
**Screen Savers Lag Bady And Crash After being Applied MacBook Becomes Unresponsive Or Slow

My Specs MacBook Pro Mid 2012 (Non-Retina)
intel i5 Processor 2.5GHz
intel HD Graphics 4000
16GB DDR3 Kingston Ram
2TB Kingston SSD

**To Reproduce**
1. Go to System Preferences 
2. Click on 'Desktop & Screensavers'
3. Use The (Drift) Screen Saver and the (Flurry)

**Expected behavior**
Once Set a ScreenSaver It should Work and Run smoothly and Wake after Touch or imput but all I get is Either a black screen and unresponsive or a really slow laggy screensaver that u can tell its having a hard time running.

**Desktop (please complete the following information):**
 - Upgrading from Catalina To Big Sur 1.3 (Release)

 - Mac Model: 13" 2012 MacBook Pro
 - Version 11.3 (20E232)

**Comment by Monkiey** [comment] 2021-05-01 20:17
This is an issue with macOS not patched sure so there is nothing the developer of patched sur can do about it please close this issue. If you want to fix the issue suggest downgrading back to Catalina or use a diffrent screnaver.

**Comment by BenSova** [comment] 2021-05-01 20:17
This is a limitation on performance because of the CPU and terribly coded screensavers, not a bug with this patcher.

**Closed by BenSova** 2021-05-01 20:17 UTC
