### ISSUE TITLE
Installation fails when password contains shell specials 

### ISSUE THREAD

**Issue by r10r** [BenSova/Patched-Sur#227] opened 2021-01-28 18:44 UTC
**Describe the bug**

Entering password at `Download Install Assistant Package` fails.
Dialog is marked in red.

**To Reproduce**

* Change your password to `foobar$123`
* Try installation with this password.

**Expected behavior**

Installation should continue.

**Assumption** 

I never used swift but I suspect that the shell callout must escape shell specials within password (or something similar)

https://github.com/BenSova/Patched-Sur/blob/11136e0dff66d92bdd213d45323ed7cb9e4293c8/Patched%20Sur%20-%20For%20Catalina/InstallPackageView.swift#L271

**Comment by BenSova** [comment] 2021-01-28 19:13
This is a duplicate issue. It already escapes `"`, `'` and `\`, but I know I need to add more options. Either way, I'm going to close it because it is tracked in another issue

**Comment by r10r** [comment] 2021-01-28 19:49
Thanks for your fast response. Please add a link to the  to the duplicate issue when you close it.
Hmm, and maybe It would be nice if you suggest changing the user password within the install instructions until this is fixed. 

Thanks for your work!

**Comment by BenSova** [comment] 2021-01-28 22:37
Most people have alphanumeric passwords, maybe with the addition `?` or `!` so it's not a big thing I want point out in the readme. 

#46 is the issue this is a duplicate of, so I'll close it and if anyone wants to make a list of special characters that do not work, say it there.

**Closed by BenSova** 2021-01-28 22:37 UTC
Labels: bug
