### ISSUE TITLE
csr-active-config appears to be set incorrectly

### ISSUE THREAD

**Issue by rpatterson86** [BenSova/Patched-Sur#27] opened 2020-11-13 19:39 UTC
after install when I try to patch kext I get this error

csr-active-config appears to be set incorrectly:
csr-active-config	%7f%00%00%00

To fix this, please boot the setvars EFI utility, then boot back into macOS
and try again. Or if you believe you are seeing this message in error, try the
`--force` command line option.

any suggestions?

**Comment by AaronF** [comment] 2020-11-13 23:54
I'm getting the same/similar issue on my 2013 iMac as well 🤔 I've tried rerunning the EFI Boot tool but no luck. Everything seems to be working though, but would be good to run the patcher.

![Screenshot 2020-11-13 at 22 59 40](https://user-images.githubusercontent.com/206194/99131603-899a0400-260b-11eb-8f86-82af4e1edf6e.png)

**Comment by kaladark** [comment] 2020-11-13 23:56
> after install when I try to patch kext I get this error
> 
> csr-active-config appears to be set incorrectly:
> csr-active-config %7f%00%00%00
> 
> To fix this, please boot the setvars EFI utility, then boot back into macOS
> and try again. Or if you believe you are seeing this message in error, try the
> `--force` command line option.
> 
> any suggestions?

Same error in Mac Mini Late 2012 :( All appear ok except wifi

**Comment by dpamping** [comment] 2020-11-13 23:58
Same here on a 2013 late iMac. Airdrop not working.

**Comment by AaronF** [comment] 2020-11-14 00:02
Wonder if it's related to System Integrity Protection still being enabled? @BenSova Do we have to have SIP disabled for the patcher to work? If so, can we re-enable it after?

**Comment by BenSova** [comment] 2020-11-14 00:07
Yeah, but the EFI Boot should turn it off. You can turn it back on, but I'm not sure how Big Sur would react, the last time I tried I got a whole bunch of kernel panics. I think I can add an option to get around this, but it'll be a little bit before I do.

**Comment by BenSova** [comment] 2020-11-14 00:08
Also, I think this is a duplicate of #21.

**Comment by dpamping** [comment] 2020-11-14 00:09
I have made the wifi boot and now working for me the airdrop

**Comment by rpatterson86** [comment] 2020-11-14 00:50
I have checked and SIP is disabled. would starting the installation over again have any chance of fixing the issue?

**Comment by dpamping** [comment] 2020-11-14 13:00
Having the same problem one day later with Airdrop

**Comment by BenSova** [comment] 2020-11-14 17:40
@dpamping Late 2013 iMacs don't require patching the kexts for everything to work.

**Comment by donmichele1** [comment] 2020-11-14 17:46
> I'm getting the same/similar issue on my 2013 iMac as well 🤔 I've tried rerunning the EFI Boot tool but no luck. Everything seems to be working though, but would be good to run the patcher.
> 
> ![Screenshot 2020-11-13 at 22 59 40](https://user-images.githubusercontent.com/206194/99131603-899a0400-260b-11eb-8f86-82af4e1edf6e.png)

exactly the same with me. On iMac late 2013 it makes no difference, true, but mbpro mid 2012 has no more wifi

**Comment by dpamping** [comment] 2020-11-14 18:49
> @dpamping Late 2013 iMacs don't require patching the kexts for everything to work.

Okay. But having problems with airdrop on the first minutes after boot.

**Comment by dpamping** [comment] 2020-11-14 18:50
> > @dpamping Late 2013 iMacs don't require patching the kexts for everything to work.
> 
> Okay. But having problems with airdrop on the first minutes after boot. Finder stuck with the beach ball If I select airdrop on the first minutes.

**Comment by donmichele1** [comment] 2020-11-16 15:05
does meanwhile a workaround exist to do the post install Patch kexts successfully?

**Comment by donmichele1** [comment] 2020-11-16 23:29
mbpro 13" mid 2012 - finally fixed it: boot in install bigsur USB stick, go to terminal and execute "csrutil disable" and "csrutil authenticated-root disable". afterwards you should be able to execute patch-kexts.sh successfully and get your wifi back.

**Comment by ishaan26** [comment] 2020-11-17 20:50
> mbpro 13" mid 2012 - finally fixed it: boot in install bigsur USB stick, go to terminal and execute "csrutil disable" and "csrutil authenticated-root disable". afterwards you should be able to execute patch-kexts.sh successfully and get your wifi back.

I was having the same issue with csr-active-config on my macbook pro 13" mid 2012 non retina. I followed the guide from @barrykn's [micropatcher](https://github.com/barrykn/big-sur-micropatcher) (step 15) and ran `patch-kexts.sh` from the USB installer's terminal without having to disable csrutil. This appears to fix it as the wifi is working now.

**Comment by BlueG6o** [comment] 2020-11-19 15:50
So I found out why I got this error. My Wifi worked ootb, but I thought the patch was needed for something else...maybe :)

The reason is in the picture. 

![Bildschirmfoto 2020-11-19 um 16 49 41](https://user-images.githubusercontent.com/74673121/99689464-529e7500-2a87-11eb-84b9-d9f9a8a46de3.png)

**Comment by BenSova** [comment] 2020-12-06 03:37
Yeah, so I'm an idiot that I did not realize this earlier, but at least I figured it out at some point. The EFI Boot utility when it is made decides whether or not to include code to turn off SIP. Of course, the only time it will do this without you explicitly telling it to is with a Late 2013 iMac. Therefore, booting into the EFI Boot will always fix this issue because it's not an issue on Late 2013 iMacs, just code working as intended. I'm not going to close this yet, because in the next release I'll add a check for the Mac model and tell the user they don't need to patch their kexts.

**Comment by jxklusive** [comment] 2021-01-05 14:27
> mbpro 13" mid 2012 - finally fixed it: boot in install bigsur USB stick, go to terminal and execute "csrutil disable" and "csrutil authenticated-root disable". afterwards you should be able to execute patch-kexts.sh successfully and get your wifi back.

I tried this but it keeps saying my password is incorrect when I boot back into the usb.

**Comment by jxklusive** [comment] 2021-01-05 14:29
At the macOS recovery screen it say to pick a user that you know the password for. I type in my password but it says it’s incorrect

**Comment by BenSova** [comment] 2021-01-05 22:17
@jxklusive Just boot into the EFI Boot on your USB. If you have a Late 2013 iMac you can skip the patch kexts step.

**Comment by BenSova** [comment] 2021-01-19 00:32
![Screen_Shot_2021-01-18_at_4 50 42_PM](https://user-images.githubusercontent.com/65474198/104973723-d951ce80-59b2-11eb-9289-b9cc179952c0.png)
This will show up when you try to enter the Patch Kexts section on Late 2013 iMacs.

**Comment by BenSova** [comment] 2021-02-11 07:09
Released the fix! So, this should no longer be an issue.

**Closed by BenSova** 2021-02-11 07:09 UTC
Labels: Proofing Coming
