### ISSUE TITLE
Wifi kext not work after close lid ( sleep laptop)

### ISSUE THREAD

**Issue by Melgan** [BenSova/Patched-Sur#646] opened 2021-06-25 08:16 UTC
**Describe Bug
After sleep ( close lid) of MacBook wifi stop working/ not finding any network, like kext not work. Only reboot solve the issue... Until I close lid 

**To Reproduce**
1. Install patched sur
2. Install kext and Restart computer
3. Connect to wifi
4. Close lid ( sleep)
5. Try to again use wifi. Not possible

**Expected behavior**
After close lid and then open I can use wifi

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from:  Catalina ( not sure version)
- Upgrading to: 11.4 release version 
 - Mac Model: 13" 2012 MacBook Pro non retina- 
 - Version MacBook Pro 9.2

**Comment by BenSova** [comment] 2021-06-26 00:12
Known issue that only applies to a minority of Macs so I can't reproduce it and debug it.  Closing this as it is a duplicate.

**Closed by BenSova** 2021-06-26 00:12 UTC

**Comment by Melgan** [comment] 2021-07-01 12:49
Hi @BenSova,
I know I'm only one of tausends. But this is pretty annoying issue, for me and for sure others with such issue. I can see 2 options:
1. Please mark on support page, that on this specific mac it is not working, here https://bensova.gitbook.io/big-sur/supported-macs , right now I can see "All 2012 and 2013 Macs are fully supported" which is not true
2. We can troubleshoot that issue, I can give you all required logs, install test patches, if this will be on system I can give you teamviewer to play with, or if needed reboots / sleeps I can do all what you want, in best time for you (even if will be night time). 
I know that this is not paid project so no way to test all issues, but I hope there is chance to solve it.


Thank you
Melgan

**Comment by BenSova** [comment] 2021-07-07 02:57
You can try enabling `System Preferences > Battery > Power Adapter > Prevent computer from sleeping automatically when the display is off`, but honestly right now I'm not going to look too far into it as I have other priorities I want to work on.
