### ISSUE TITLE
Handoff not working and some problems with iCloud in macOS 11.4 (and even 11.5)

### ISSUE THREAD

**Issue by shines75** [BenSova/Patched-Sur#678] opened 2021-07-24 03:55 UTC
Hi! There really seems to be a bug in the latest version of Patched-Sur, 0.2.1. I've a MBP 15" mid-2012 with Big Sur 11.4 patched with the latest version of Patched-Sur. I've not noticed this immediately, but after I updated my mac to Big Sur 11.4, (now, I tried to update to 11.5, but nothing changed), handoff stopped working and my mac begin to have some problems to communicate well with iCloud, (3rd party apps not synchronizing and message code of 2 factor authentication never sent to my mac).
Now, at a glance, It seemed logic to me to try all the black magic possible to fix these problems, even with the help of some guides on the web, but nothing to do. So, after 2 days I I made the decisive test: I logged in with my appleid in a fresh install of Catalina 10.15.7, (the latest version of the OS officially supported from my mac), and THESE PROBLEMS VANISHED COMPLETELY!!!
Thus, It's logical for me to think there's something wrong with Patched-Sur 0.2.1 and Big Sur 11.4 or 11.5.

**Comment by Monkiey** [comment] 2021-07-24 03:57
> Hi! There really seems to be a bug in the latest version of Patched-Sur, 0.2.1. I've a MBP 15" mid-2012 with Big Sur 11.4 patched with the latest version of Patched-Sur. I've not noticed this immediately, but after I updated my mac to Big Sur 11.4, (now, I tried to update to 11.5, but nothing changed), handoff stopped working and my mac begin to have some problems to communicate well with iCloud, (3rd party apps not synchronizing and message code of 2 factor authentication never sent to my mac).
> Now, at a glance, It seemed logic to me to try all the black magic possible to fix these problems, even with the help of some guides on the web, but nothing to do. So, after 2 days I I made the decisive test: I logged in with my appleid in a fresh install of Catalina 10.15.7, (the latest version of the OS officially supported from my mac), and THESE PROBLEMS VANISHED COMPLETELY!!!
> Thus, It's logical for me to think there's something wrong with Patched-Sur 0.2.1 and Big Sur 11.4 or 11.5.

hmm handoff works fine for me, but again I have a mac that doesn't need to worry about kexts as wifi works out of the box I a not the person to answer this question

**Comment by shines75** [comment] 2021-07-24 06:13
So why have you answered? The question now turns to Ben Sova.

**Comment by BenSova** [comment] 2021-07-24 14:02
What happens if you upgrade this fresh installed Catalina to Big Sur 11.5?

**Comment by shines75** [comment] 2021-07-24 14:35
Sincerely, I don’t wanna waste my time trying these experiments…I think the issue is in your patcher, Ben

**Comment by shines75** [comment] 2021-07-24 14:44
And by the way, I do not have this fresh install of Catalina any longer, so…

**Comment by Monkiey** [comment] 2021-07-24 14:49
> And by the way, I do not have this fresh install of Catalina any longer, so…

what ben menthes to create aCatalina installer the fresh install Catalina again and then do patched Sur again to get to Big Sur

**Comment by shines75** [comment] 2021-07-24 14:56
Yes, I’m not fool, I’ve already understood this. But again, simply I don’t wanna waste my time doing these kind of experiments that YOU SHOULD DO

**Comment by Monkiey** [comment] 2021-07-24 14:57
> Yes, I’m not fool, I’ve already understood this. But again, simply I don’t wanna waste my time doing these kind of experiments that YOU SHOULD DO

Okay, no need for this attitude I was just try to clarify that its it.

**Comment by Monkiey** [comment] 2021-07-24 14:59
I see where from coming from it seems tyou have already fresh installed ctalina sorry

**Comment by shines75** [comment] 2021-07-24 15:03
Any ideas, Ben? Have you ever noticed this bug?

**Comment by shines75** [comment] 2021-07-24 15:05
And please keep in mind that this bug does not only regard handoff but even the way the system communicates with iCloud...

**Comment by Monkiey** [comment] 2021-07-24 15:13
> And please keep in mind that this bug does not only regard handoff but even the way the system communicates with iCloud...

Have you tired logging out of your iCloud account than logging back in

**Comment by shines75** [comment] 2021-07-24 15:14
Many times: nothing to do

**Comment by shines75** [comment] 2021-07-24 15:15
But I'd like Ben to express his opinion on the matter

**Comment by Monkiey** [comment] 2021-07-24 15:16
> But I'd like Ben to express his opinion on the matter

yeah good idea he knows best since he made the patcher

**Comment by shines75** [comment] 2021-07-24 15:17
Indeed

**Comment by BenSova** [comment] 2021-07-24 15:41
> Sincerely, I don’t wanna waste my time trying these experiments…I think the issue is in your patcher, Ben

It works on my machine so it's something with your install. Plus, if it worked before then randomly stopped working, there's another element at play. The patches don't just stop working, there's something else messing with them hence why I suggested seeing what a clean install does.

**Comment by shines75** [comment] 2021-07-24 15:59
Do you really think this? Well, the issue gets represented on a fresh install of Big Sur 11.5, I’ve already tried it.

**Comment by BenSova** [comment] 2021-07-24 16:02
Well, I guess now I'm going to actually install 11.5 and see what happens.

**Comment by shines75** [comment] 2021-07-24 16:07
Ok, you’ll realize by yourself. See ya

**Comment by BenSova** [comment] 2021-07-24 16:10
![Screen Shot 2021-07-24 at 10 09 02 AM](https://user-images.githubusercontent.com/65474198/126874436-ba9aa92b-9c09-4b72-bd6b-f443931ca6e4.png)
Btw, 11.4 works fine with handoff, so I'm sure 11.5 won't make a difference (too many successes on the discord already lol), but I'll go to 11.5 anyway.

**Comment by shines75** [comment] 2021-07-24 16:20
Pay attention, Ben: if you really wanna make this try for me, try to make a fresh install of Big Sur 11.5!

**Comment by shines75** [comment] 2021-07-24 19:16
Then, What about the fresh install of Big Sur 11.5?

**Comment by BenSova** [comment] 2021-07-25 02:14
As I predicted, it works fine.

**Comment by shines75** [comment] 2021-07-25 02:34
No, This is not possible...I had tried it myself! So, What's the story? Only my mac is affected??

**Comment by shines75** [comment] 2021-07-25 02:35
And moreover, if I'm not wrong, you've my same machine!!!

**Comment by shines75** [comment] 2021-07-25 02:38
Ben?

**Comment by BenSova** [comment] 2021-07-25 03:16
> No, This is not possible

Well it happened.

> you've my same machine!!!

Mid 2012 13" MacBook Pro

> So, What's the story?

I don't know, there's too many variables to track.

**Comment by Monkiey** [comment] 2021-07-25 03:54
> No, This is not possible...I had tried it myself! So, What's the story? Only my mac is affected??

it looks like that is the case as often "the most common problems only occur for a specific scenario and won’t occur for any other scenario."

**Comment by BenSova** [comment] 2021-07-25 03:55
It's not a common problem, but it does happen for only a specific scenario.

**Comment by shines75** [comment] 2021-07-25 04:49
Well, it’s crazy…I’ve just made another fresh install of Big Sur 11.5 on my internal ssd this time, on another partition, but handoff does not work - and I suppose that even iCloud synchronization with 3rd party apps doesn’t work!!! What can I try to do? You’re the expert, you made the patcher!

**Comment by shines75** [comment] 2021-07-25 04:58
However, you talked about “variables”. Could you make me some examples? Say, just to have an idea…

**Comment by Monkiey** [comment] 2021-07-25 05:01
Variables mean all of the factors like they way your Mac is setup which can cause the issue and cause the effect

**Comment by shines75** [comment] 2021-07-25 05:35
And What may be wrong with my mac?

**Comment by shines75** [comment] 2021-07-25 05:38
I can ensure it’s all tuned up very well…I’m manic with my mac!!!

**Comment by shines75** [comment] 2021-07-25 07:05
And now, I’m left with a “buggy” fresh install of Big Sur 11.5, on my internal ssd!!

**Comment by shines75** [comment] 2021-07-25 07:13
It’s ridiculous, Ben!!! 🙄

**Comment by BenSova** [comment] 2021-07-25 12:47
Maybe Big Sur and your iCloud don't play well. But if you step back, it's a iCloud is a software not hardware problem, and Handoff requires iCloud iirc so the source of your problem isn't related to the patcher.

I did some quick googling and found [this](https://forums.macrumors.com/threads/icloud-not-syncing.2280756/) and other things, that prove that it could be something software wise happening on supported Macs.

**Comment by shines75** [comment] 2021-07-25 13:09
Mmm, interesting…it can be, who knows. But I believe if I had a supported mac, probably I’d never had this kind of issues on my mac. Let’s say that it’s likely to believe that.

**Comment by shines75** [comment] 2021-07-25 13:18
In short, what I meant It’s there’s difference from an original thing and an adapted one, that’s all.

**Comment by shines75** [comment] 2021-07-25 13:26
But I’m also saying the obvious…naaa, maybe, I can only hope that your upcoming Monterey Patcher will fix the things for me. Excuse me, Ben, if I bothered you.

**Comment by BenSova** [comment] 2021-07-25 15:49
> But I believe if I had a supported mac, probably I’d never had this kind of issues on my mac. Let’s say that it’s likely to believe that.

Just because you're likely to believe it doesn't mean it's likely it's true. 🤷‍♂️

Software not hardware, like I said before. Though that's a little bit misleading. Here's a better scope of problems and whether or not they're related to Patched Sur:

- ❌ Service Bugs (ex. iCloud)
- ❌ Software working with services Bugs (ex. iCloud Sync)
- ❌ Software Bugs* (ex. Local Applications and OS, installation of software)
- ✅ Software working with Hardware (ex. WiFi, Bluetooth, Graphics Acceleration)
- ❌ Hardware problems (ex. firmware/hardware bricking, broken parts)

There are rare cases where it's different, but 99% of the time the patcher is only at fault if it's a problem with software working with hardware (ex. your WiFi card still works without patching, but the software doesn't know how to work with it so it needs different drivers/kexts).

**Comment by BenSova** [comment] 2021-07-25 15:53
I'm curious, if you make a new user account on your Mac using a **new** (key word: new) iCloud account, does iCloud work?

**Comment by shines75** [comment] 2021-08-08 02:38
After googling around a lot, I've come to the conclusion It really sounds like a hardware issue. I'll explain myself better: The issue is certainly due to **an in compatibility of my machine and Big Sur**...in fact, the issue now is the same even with a fresh install of Big Sur patched with OCP, (**OCP, not OCP + Patched Sur**). The conclusion is that most probably, because I continued to update my mac with the most recent firmware updates, (with an installation of Catalina I have on an external HD), one of these updates broke the support of handoff with Big Sur. Do the accounts add up now, Ben?

**Comment by shines75** [comment] 2021-08-08 02:52
The question now is: if I'm right, what can I do to solve this issue?

**Comment by BenSova** [comment] 2021-08-08 02:58
OCLP follows my chart/checklist/whatever thing I sent earlier (for the most part), so it doesn't change my mind. Also the firmware wouldn't really mess with the software too much, so that shouldn't make a difference.
And honestly I don't have an answer to your question, it's just not related to the patcher.

**Comment by BenSova** [comment] 2021-08-08 02:59
Did you ever even try this?
> I'm curious, if you make a new user account on your Mac using a new (key word: new) iCloud account, does iCloud work?

**Comment by shines75** [comment] 2021-08-08 05:25
Sincerely, I don't feel like making this kind of experiments...instead can you confirm my hypothesis, that is, it's my mac that definitely has an incompatibility, (handoff not working), with Big Sur, now?

**Comment by Monkiey** [comment] 2021-08-08 05:26
> Sincerely, I don't feel like making this kind of experiments...instead can you confirm my hypothesis, that is, it's my mac that definitely has an incompatibility, (handoff not working), with Big Sur, now?

It’s not even that hard to make an new account just try what Ben did that is how we troubleshoot problems

**Comment by shines75** [comment] 2021-08-08 05:58
Okay Monkiey, I'll try later and I'll let you know.

**Comment by shines75** [comment] 2021-08-08 08:22
Well, I've to fair: contrary to what I thought earlier, there aren't any issues regarding iCloud sync with 3rd party apps, even on my primary AppleID; the only issue regards the 2 factor authentication code not sent to my mac running Big Sur. But unfortunately, I was not able to replicate this issue on the new AppleID (the sending of the code is at Apple's discretion).

**Comment by shines75** [comment] 2021-08-08 09:07
However, this is a minor issue; the major is handoff not working.

**Comment by shines75** [comment] 2021-08-08 10:28
I don't know if these 2 screenshots could help:

![Istantanea 2021-08-08 alle 12 25 10](https://user-images.githubusercontent.com/87176050/128628921-dc73ff3c-6922-4b3b-98fe-17dbf286d093.png)
![Istantanea 2021-08-08 alle 12 26 49](https://user-images.githubusercontent.com/87176050/128628923-44b9693c-7c3e-4766-8f1a-6f2137d03adb.png)

**Comment by Monkiey** [comment] 2021-08-08 18:42
yeah it seems your mac serial number is messed up like it says unavailable that can definitely can affect your icloud services as they depend on your mac serial number

**Comment by BenSova** [comment] 2021-08-08 21:46
> Sincerely, I don't feel like making this kind of experiments

Well it works for me so..... your Mac, you have to do something to see where the problem is.

> instead can you confirm my hypothesis, that is, it's my mac that definitely has an incompatibility, (handoff not working), with Big Sur, now?

I answered that already

> yeah it seems your mac serial number is messed up like it says unavailable

Lol, yeah.... that's a problem. Idk how that happened.

**Comment by shines75** [comment] 2021-08-09 04:40
Yes, it’s true: my mac serial number is unavailable. But this shouldn’t affect iCloud services, because on Catalina and below, handoff and the whole iCloud work fine.

**Comment by BenSova** [comment] 2021-08-09 14:23
Things change, security requirements change, it could easily be something as simple as they now use your serial number to help with handoff to make sure the wrong signals don't go to the wrong Macs.

**Comment by shines75** [comment] 2021-08-09 15:19
Mmmm, interesting, but it's not a sure thing, it's only supposed by you. In fact, this morning, I called the nearest Apple service center, and they said this thing is only a silliness. In other words, the lack of the serial number absolutely does not affect the proper functioning of the mac.

**Comment by BenSova** [comment] 2021-08-09 15:36
Apple Support is like many virtual assistants (but of course with a better understanding of what you're saying), they only know what they were told to know. They're not the devs, they don't know much about the interworking of the software.

Also please stop doubting literally everything I say. It only makes understanding this problem harder. I still don't know of you even did my "experiment" tbh. (And if you did, how you did it, for example: Did you use that same new Apple ID on another device?)

**Comment by shines75** [comment] 2021-08-09 16:36
For the first question, then you're pretty sure of what you say: serial number is important for proper iCloud working in Big Sur and later.

For the second question: I already answered to this question, see above.

**Comment by BenSova** [comment] 2021-08-09 16:38
This? 

>  But unfortunately, I was not able to replicate this issue on the new AppleID

That says the issue is with your Apple ID.

**Comment by shines75** [comment] 2021-08-09 16:50
Naaa, I've tried to use my AppleID with Catalina, and I had no problem, everything worked, even handoff.

**Comment by BenSova** [comment] 2021-08-09 16:52
Catalina != Big Sur
Thing change.

**Comment by shines75** [comment] 2021-08-09 16:56
We want to bet, that when I buy my new MacBook Pro 2017, (on December), my AppleID will not cause me any problems, neither in Big Sur, nor in Monterey?

**Comment by BenSova** [comment] 2021-08-09 16:58
You proved what I said before. If handoff works with an alt Apple ID, it's something to do with your Apple ID and NOT software interacting with hardware. That's the only logical thing to think it's it?

**Comment by shines75** [comment] 2021-08-09 17:00
NOOO: you misunderstood!!! Handoff didn't work even with the alt AppleID!!!

**Comment by BenSova** [comment] 2021-08-09 17:01
Jeez calm down. You switched Apple IDs on your iPhone too right?

**Comment by shines75** [comment] 2021-08-09 17:01
Yes, of course.

**Comment by BenSova** [comment] 2021-08-09 17:01
What I was typing before you replied:
Not everything is the patcher. macOS is something called not perfect. Nothing is perfect. You can't have perfectly compatible data all the time. Incompatible data is actually where I think the problem is.

**Comment by BenSova** [comment] 2021-08-09 17:02
What iOS version?

**Comment by BenSova** [comment] 2021-08-09 17:02
(For reference: I'm using macOS 11.5.1 to iOS 15b4)

**Comment by shines75** [comment] 2021-08-09 17:04
An iPhone XS Max with iOS 14.7.1. And I have an iPad Pro 201 with iPadOS 14.7.1.

**Comment by shines75** [comment] 2021-08-09 17:04
iPad Pro 2018, pardon.

**Comment by shines75** [comment] 2021-08-09 17:06
but honestly, this seems like a wrong track to me

**Comment by BenSova** [comment] 2021-08-09 17:11
From what I'm seeing, everything seems like the wrong track to you. I'm trying to pin point it, you're trying to say that it's 100% the patcher's fault and only the patcher's fault and that this needs to be fixed and that it's impossible that mine works but yours doesn't and that your future Mac won't have these problems and that you can't do the experiments because it's clearly the patcher's fault. Do you see where my frustration is? At this rate I just want to close the issue and move on because you're so sure of your hypothesis but can't back it up while I'm trying to test mine. That's my two cents. 

Can you send a screen recording from both devices of what you're doing to test it?

https://user-images.githubusercontent.com/65474198/128745689-f92f23ce-e80a-4b5b-a27c-35fd86aad104.mov

https://user-images.githubusercontent.com/65474198/128745615-110dd598-f7ed-4c33-a768-96d1431d5ea4.mov

**Comment by shines75** [comment] 2021-08-09 17:31
https://user-images.githubusercontent.com/87176050/128748586-c62e1155-d679-4cd6-bfb0-67d2ad5ee96f.mov


https://user-images.githubusercontent.com/87176050/128748597-ae12ae4a-d7e6-46f4-bca5-1676373fbfde.mov

(Nothing displayed on Mac)

**Comment by shines75** [comment] 2021-08-09 17:38
Do you know a way to reinsert the serial number in my mac (i.e. by terminal)?

**Comment by shines75** [comment] 2021-08-09 17:50
Maybe, I've found a solution to my issue: [youtube video by dosdude1](https://www.youtube.com/watch?v=GYkGgugiVHA) I'll let you know.

**Comment by shines75** [comment] 2021-08-09 18:45
Hurray! Blank Board Serialiser did the magic for me!! Now iCloud and handoff work wonders!!! Thank you, Ben, for your patience and cleverness.

**Closed** 2021-08-09 18:45 UTC

**Comment by Monkiey** [comment] 2021-08-09 18:52
> Hurray! Blank Board Serialiser did the magic for me!! Now iCloud and handoff work wonders!!! Thank you, Ben, for your patience and cleverness.

I am glad I spotted the serial number and raised awareness to it i glad your issue is fixed

**Comment by BenSova** [comment] 2021-08-09 18:53
So it was the serial number...
Anyways, awesome!
