### ISSUE TITLE
Error 1 X 56

### ISSUE THREAD

**Issue by bigd7304** [BenSova/Patched-Sur#31] opened 2020-11-14 06:38 UTC
Hi,
getting the error message 1x56 when downloading the MacSur release file. Have tried 3 times now and always same error. does anybody have an idea? Thanks
![Screenshot at Nov 14 07-31-25](https://user-images.githubusercontent.com/74445929/99141502-40b66f80-264c-11eb-9820-ae171abc3c71.png)

**Comment by doellinger** [comment] 2020-11-14 16:35
also stuck with this error. any help?

**Comment by andymayer** [comment] 2021-01-24 21:54
I am also stuck with this. Any ideas?

**Comment by BenSova** [comment] 2021-01-24 23:09
Click to copy exists for a reason. Click the red box, paste the contents here.

**Comment by andymayer** [comment] 2021-01-25 00:32
Looks to me like this is a duplicate of https://github.com/BenSova/Patched-Sur/issues/177

I resolved it by downloading the installer on another machine

**Comment by BenSova** [comment] 2021-01-30 15:46
That's Error 1x7 not Error 1x56, either way I'm closing this because no one responded with the message asking for someone to click on the red box and paste the full error here.

**Closed by BenSova** 2021-01-30 15:46 UTC
