### ISSUE TITLE
there was an error parsing the Info.plist

### ISSUE THREAD

**Issue by aydenstanton** [BenSova/Patched-Sur#399] opened 2021-03-14 03:01 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Upgrading from: [e.g. Catalina v10.15.7]
- Upgrading to: [e.g. Big Sur v11.1 Beta 1, Big Sur v11.0]
 - Mac Model: [e.g. 13" mid 2012 MacBook Pro]
 - Version [e.g. v0.1.2]

**Additional context**

If there are any red boxes, click on them to copy the logs.

Error 1x250
Message: "Password:Erasing disk: 0%... 10%... 20%... 30%... 100%
2021-03-14 02:55:26.196 createinstallmedia[29698:254692] There was an error parsing the Info.plist for the bundle at URL <0x7f9d03ab1b00>: NSCocoaErrorDomain - 3840
Couldn't mount dmg /Volumes/Install macOS Big Sur/Install macOS Big Sur.app/Contents/SharedSupport/SharedSupport.dmg (error code 110)The bless of the installer disk failed."
Output: "Copying to disk: 0%... 10%... 20%... 30%... 40%... 50%... 60%... 70%... 80%... 90%... 100%
Making disk bootable...
Couldn't find InstallInfo.plist"

**Comment by BenSova** [comment] 2021-03-14 04:00
Duplicate of #320, and I'm sure just trying again will fix it anyway.

**Closed by BenSova** 2021-03-14 04:00 UTC

**Comment by aydenstanton** [comment] 2021-03-14 04:03
thank you
